# Site settings
title: Jonathan Webb
email: jonathan.webb@mail.utoronto.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jwebbed
github_username:  jwebbed

# Build settings
markdown: kramdown


navigation:
  - title: Portfolio
    link: /portfolio/
  - title: Blog
    link: /blog/
